/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controller;
import javax.swing.JOptionPane;
import Modelo.*;

/**
 *
 * @author plupy
 */
public class FrMenuPrincipal extends javax.swing.JFrame {
    Controller controlador = new Controller();
    
    /**
     * Creates new form MenuPrincipal
     */
    public FrMenuPrincipal(Controller controlador) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //se setea los modelos a la interfaz de las listas
        jListNombres.setModel(controlador.getModeloListaNombres());
        jListTareas.setModel(controlador.getModeloListaTareas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbNombres = new javax.swing.JLabel();
        btnAbonar = new javax.swing.JButton();
        btnEliminarPersona = new javax.swing.JButton();
        lbCantidadQueDebe = new javax.swing.JLabel();
        lbTareasPendientes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNombres = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListTareas = new javax.swing.JList<>();
        btnAgregarNombre = new javax.swing.JButton();
        btnEliminarTarea = new javax.swing.JButton();
        btnAgregarTarea = new javax.swing.JButton();
        txtNuevaPersona = new javax.swing.JTextField();
        txtAbono = new javax.swing.JTextField();
        lbAbono = new javax.swing.JLabel();
        txtCantidadQueDebe = new javax.swing.JLabel();
        lbNuevaPersona = new javax.swing.JLabel();
        txtTareaNueva = new javax.swing.JTextField();
        lbTareaNueva = new javax.swing.JLabel();
        lbIngresaSuPrecio = new javax.swing.JLabel();
        txtIngresaSuPrecio = new javax.swing.JTextField();
        txtIngresaFecha = new javax.swing.JTextField();
        lbIngresaFecha = new javax.swing.JLabel();
        lbFechaTarea = new javax.swing.JLabel();
        btnGuardarDatos = new javax.swing.JButton();
        btnCargarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbTitulo.setText("Sistema de tareas");

        lbNombres.setText("Nombres");

        btnAbonar.setText("Abonar");
        btnAbonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonarActionPerformed(evt);
            }
        });

        btnEliminarPersona.setText("Eliminar persona");
        btnEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPersonaActionPerformed(evt);
            }
        });

        lbCantidadQueDebe.setText("Cantidad que debe: $");

        lbTareasPendientes.setText("Tareas pendientes:");

        jListNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListNombresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListNombres);

        jListTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTareasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListTareas);

        btnAgregarNombre.setText("Agregar nombre");
        btnAgregarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNombreActionPerformed(evt);
            }
        });

        btnEliminarTarea.setText("Elliminar tarea");
        btnEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTareaActionPerformed(evt);
            }
        });

        btnAgregarTarea.setText("Agregar tarea");
        btnAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTareaActionPerformed(evt);
            }
        });

        lbAbono.setText("¿desea abonar?");

        txtCantidadQueDebe.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        lbNuevaPersona.setText("Ingrese nombre de la nueva persona:");

        lbTareaNueva.setText("Ingresa nombre de la tarea nueva:");

        lbIngresaSuPrecio.setText("Ingresa su precio");

        lbIngresaFecha.setText("Ingresa fecha límite:");

        btnGuardarDatos.setText("Guardar datos");
        btnGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDatosActionPerformed(evt);
            }
        });

        btnCargarDatos.setText("Cargar datos");
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbNombres)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnEliminarPersona))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(btnAgregarNombre))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNuevaPersona)
                                    .addComponent(txtNuevaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnCargarDatos)
                        .addGap(30, 30, 30)
                        .addComponent(btnGuardarDatos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAbono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 314, Short.MAX_VALUE)
                                .addComponent(btnAbonar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTareasPendientes)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbFechaTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnEliminarTarea))
                                .addComponent(btnAgregarTarea)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbCantidadQueDebe)
                                    .addGap(28, 28, 28)
                                    .addComponent(txtCantidadQueDebe, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbAbono))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTareaNueva)
                            .addComponent(txtTareaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIngresaSuPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbIngresaSuPrecio))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIngresaFecha)
                            .addComponent(txtIngresaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 57, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(lbTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTitulo)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTareaNueva)
                            .addComponent(lbIngresaSuPrecio)
                            .addComponent(lbIngresaFecha)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbNuevaPersona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnAgregarTarea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTareasPendientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbFechaTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbCantidadQueDebe))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNuevaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTareaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIngresaSuPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIngresaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarNombre)
                        .addGap(11, 11, 11)
                        .addComponent(lbNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarPersona)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lbAbono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbonar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarDatos)
                    .addComponent(btnCargarDatos))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(txtCantidadQueDebe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNombreActionPerformed
        //Botón agregar nombre
        String nombrePersona = txtNuevaPersona.getText();
        try{
            if(nombrePersona.equals("")){
                throw new CampoVacioException("Falta llenar un campo");
            }
            Persona nuevaPersona = controlador.agregarPersona(nombrePersona);
            // actualiza campos
            txtCantidadQueDebe.setText(nuevaPersona.getDineroAPagar()+"");
            jListNombres.setModel(controlador.getModeloListaNombres());
            txtNuevaPersona.setText("");    //setea jText en blanco
        }
        catch(CampoVacioException ex1){
            JOptionPane.showMessageDialog(this, "Debe llenar el campo del nombre de la persona para agregar", "Error al agregar Persona", JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_btnAgregarNombreActionPerformed

    private void btnEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonaActionPerformed
        //Botón eliminar nombre
        int personaSeleccionada = jListNombres.getSelectedIndex();
        controlador.eliminarPersona(personaSeleccionada);
        //  setea campos en blanco
        lbFechaTarea.setText("");
        txtCantidadQueDebe.setText("");
        //  actualiza las listas
        jListNombres.setModel(controlador.getModeloListaNombres());
        jListTareas.setModel(controlador.getModeloListaTareas());
    }//GEN-LAST:event_btnEliminarPersonaActionPerformed

    private void btnAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTareaActionPerformed
        //Botón agregar tarea
        int personaSeleccionada = jListNombres.getSelectedIndex();     //índice de la persona dentro de la lista
        String nombreTarea = txtTareaNueva.getText();
        int precioTarea = Integer.parseInt(txtIngresaSuPrecio.getText());
        String fechaEntrega = txtIngresaFecha.getText();
        try{
            controlador.agregarTarea(personaSeleccionada, nombreTarea, precioTarea, fechaEntrega);
            //  actualiza campos
            txtTareaNueva.setText("");
            txtIngresaSuPrecio.setText("");
            txtIngresaFecha.setText("");
            txtCantidadQueDebe.setText(controlador.getListaPersonas().get(personaSeleccionada).getDineroAPagar()+"");
            jListTareas.setModel(controlador.getModeloListaTareas());
        }
        catch(ArrayIndexOutOfBoundsException ex1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar a una persona de la lista", "Error al agregar tarea", JOptionPane.WARNING_MESSAGE);
        }
        catch(NumberFormatException ex2){
            JOptionPane.showMessageDialog(this, "Faltó llenar el nombre o precio de la tarea", "Error al agregar tarea", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarTareaActionPerformed

    private void btnEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTareaActionPerformed
        //Botón eliminar tarea
        try{
            int personaSeleccionada = jListNombres.getSelectedIndex();
            int tareaAEliminar = jListTareas.getSelectedIndex();
            controlador.eliminarTarea(personaSeleccionada, tareaAEliminar);
            //  actualiza campos
            lbFechaTarea.setText("");
            jListTareas.setModel(controlador.getModeloListaTareas());
        }
        catch(ArrayIndexOutOfBoundsException ex1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una tarea de la lista", "Error al eliminar tarea", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarTareaActionPerformed

    private void btnAbonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonarActionPerformed
        //Botón abonar
        try{
            int personaAAbonar = jListNombres.getSelectedIndex();
            int cantidadAAbonar = Integer.parseInt(txtAbono.getText());
            controlador.abonar(personaAAbonar, cantidadAAbonar);
            //  actualiza campos
            txtCantidadQueDebe.setText(controlador.getListaPersonas().get(personaAAbonar).getDineroAPagar()+"");
            txtAbono.setText("");
        }
        catch(ArrayIndexOutOfBoundsException ex1){
            JOptionPane.showMessageDialog(this, "Verifique que hay sido seleccionada una persona", "Error de selección", JOptionPane.WARNING_MESSAGE);
        }
        catch(NumberFormatException ex2){
            JOptionPane.showMessageDialog(this, "No ingreso ningún monto", "Error al abonar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAbonarActionPerformed

    private void jListNombresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListNombresMouseClicked
        //Click en la lista de nombres
        try{
            int indiceLista = jListNombres.getSelectedIndex();
            controlador.actualizarTareas(indiceLista);
            //  actualiza campos
            txtCantidadQueDebe.setText(controlador.getListaPersonas().get(indiceLista).getDineroAPagar()+"");
            lbFechaTarea.setText("");
        }
        catch(ArrayIndexOutOfBoundsException ex2){
            JOptionPane.showMessageDialog(this, "La lista de personas está vacía", "Lista vacía", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jListNombresMouseClicked

    private void jListTareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTareasMouseClicked
        //Click en la lista de Tareas
        try{
            int tareaSeleccionada = jListTareas.getSelectedIndex();
            int personaSeleccionada = jListNombres.getSelectedIndex();
            lbFechaTarea.setText(controlador.getListaPersonas().get(personaSeleccionada).getTareas().get(tareaSeleccionada).getFechaLimite());
        }
        catch(ArrayIndexOutOfBoundsException ex1){
            JOptionPane.showMessageDialog(null, "Faltó seleccionar una persona o una tarea, verifíquelo", "Error de selección", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jListTareasMouseClicked

    private void btnGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDatosActionPerformed
        //btnGuardarDatos
        controlador.serializarDatos();
    }//GEN-LAST:event_btnGuardarDatosActionPerformed

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
        //btnCargarDatos
        controlador.deserializarDatos();
        jListNombres.setModel(controlador.getModeloListaNombres());
    }//GEN-LAST:event_btnCargarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private Controller controlador;
            public void run() {
                new FrMenuPrincipal(this.controlador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbonar;
    private javax.swing.JButton btnAgregarNombre;
    private javax.swing.JButton btnAgregarTarea;
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnEliminarPersona;
    private javax.swing.JButton btnEliminarTarea;
    private javax.swing.JButton btnGuardarDatos;
    private javax.swing.JList<String> jListNombres;
    private javax.swing.JList<String> jListTareas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbAbono;
    private javax.swing.JLabel lbCantidadQueDebe;
    private javax.swing.JLabel lbFechaTarea;
    private javax.swing.JLabel lbIngresaFecha;
    private javax.swing.JLabel lbIngresaSuPrecio;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbNuevaPersona;
    private javax.swing.JLabel lbTareaNueva;
    private javax.swing.JLabel lbTareasPendientes;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtAbono;
    private javax.swing.JLabel txtCantidadQueDebe;
    private javax.swing.JTextField txtIngresaFecha;
    private javax.swing.JTextField txtIngresaSuPrecio;
    private javax.swing.JTextField txtNuevaPersona;
    private javax.swing.JTextField txtTareaNueva;
    // End of variables declaration//GEN-END:variables
}
